#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Users/zeyadal-harbi/Desktop/app/flutter"
export "FLUTTER_APPLICATION_PATH=/Users/zeyadal-harbi/Desktop/app/n"
export "FLUTTER_TARGET=/Users/zeyadal-harbi/Desktop/app/n/lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "SYMROOT=${SOURCE_ROOT}/../build/ios"
export "OTHER_LDFLAGS=$(inherited) -framework Flutter"
export "FLUTTER_FRAMEWORK_DIR=/Users/zeyadal-harbi/Desktop/app/flutter/bin/cache/artifacts/engine/ios"
export "FLUTTER_BUILD_NAME=1.9.4"
export "FLUTTER_BUILD_NUMBER=3001"
export "DART_DEFINES=flutter.inspector.structuredErrors%3Dtrue"
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=true"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=.packages"
